# Generated by Django 4.0.6 on 2022-08-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamillePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille_plante', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nommolecule', models.CharField(default='any_name', max_length=200)),
                ('formule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologie', models.CharField(max_length=200)),
                ('symptomes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_medicinale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Substance médicinale')),
                ('zang_fu', models.CharField(blank=True, max_length=200, null=True, verbose_name='ZANG / FU')),
                ('saveur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Saveur')),
                ('nature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature')),
                ('action', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Action')),
                ('posologie', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Posologie')),
                ('pao_zi', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Pao Zi')),
                ('contre_indications', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Contre-indications')),
                ('fonctions', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Fonctions')),
                ('cibles_clefs', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Cibles clefs')),
                ('indications', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Indications (= symptômes)')),
                ('textes_classiques', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Shen Nong Ben Cao Jing et autres textes classiques')),
                ('interets_therapeutiques', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Intérêts thérapeutiques')),
                ('ZZJ_HXS_FSL', models.TextField(blank=True, max_length=2000, null=True, verbose_name='ZZJ - HXS - FSL')),
                ('pharmacopee_contemporaine', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Pharmacopée contemporaine')),
                ('precisions_PS', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Précisions PS')),
                ('grandes_combinaisons', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Grandes combinaisons')),
                ('incompatibilite_alimentaire', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Incompatibilité alimentaire')),
                ('prudence_medicamenteuse', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Prudence médicamenteuse')),
                ('contre_indications_medicamenteuses', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Contre-indications médicamenteuses')),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompreparation', models.CharField(default='any_name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlanteFamillePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille_plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.familleplante')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.plante')),
            ],
        ),
        migrations.CreateModel(
            name='PathologiePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pathologie')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='MoleculePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.molecule')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.preparation')),
            ],
        ),
    ]
