# Generated by Django 4.0.6 on 2022-08-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndrome', models.CharField(default='', max_length=200)),
                ('systeme', models.CharField(default='', max_length=200)),
                ('symptomes', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='moleculepreparation',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='moleculepreparation',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='pathologiepreparation',
            name='pathologie',
        ),
        migrations.RemoveField(
            model_name='pathologiepreparation',
            name='preparation',
        ),
        migrations.DeleteModel(
            name='Molecule',
        ),
        migrations.DeleteModel(
            name='MoleculePreparation',
        ),
        migrations.DeleteModel(
            name='Pathologie',
        ),
        migrations.DeleteModel(
            name='PathologiePreparation',
        ),
        migrations.DeleteModel(
            name='Preparation',
        ),
        migrations.AddField(
            model_name='planteprescription',
            name='Prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.prescription'),
        ),
        migrations.AddField(
            model_name='planteprescription',
            name='plante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.plante'),
        ),
    ]
