# Generated by Django 4.0.6 on 2022-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0002_planteprescription_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planteprescription',
            name='intitule',
            field=models.CharField(blank=True, choices=[('JING FANG', 'JING FANG'), ('Zang fu Qui', 'Zang fu Qui')], max_length=200, null=True, verbose_name='intitulé pharmacopée'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptomes',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
