# Generated by Django 4.0.6 on 2022-08-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0004_remove_planteprescription_intitule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantePrescription',
            new_name='PlantePrescriptionJINGFANG',
        ),
    ]
