# Generated by Django 4.0.6 on 2022-08-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0005_rename_planteprescription_planteprescriptionjingfang'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantePrescriptionZangfuQui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.prescription')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.plante')),
            ],
        ),
    ]
