# Generated by Django 4.0.6 on 2022-08-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0006_planteprescriptionzangfuqui'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planteprescriptionjingfang',
            options={'verbose_name': 'JING FANG', 'verbose_name_plural': 'JING FANG'},
        ),
        migrations.AlterModelOptions(
            name='planteprescriptionzangfuqui',
            options={'verbose_name': 'Zang fu Qui', 'verbose_name_plural': 'Zang fu Qui'},
        ),
        migrations.AddField(
            model_name='prescription',
            name='remarques',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
