# Generated by Django 4.0.6 on 2022-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0007_alter_planteprescriptionjingfang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='famille_plante',
            field=models.ManyToManyField(to='myDB.familleplante'),
        ),
        migrations.DeleteModel(
            name='PlanteFamillePlante',
        ),
    ]
