# Generated by Django 4.0.6 on 2022-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0009_contact_alter_plante_interets_therapeutiques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndrome_principal', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Syndrome principal')),
                ('syndrome', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Syndrome')),
                ('causes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Causes')),
                ('symptomes_explications', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Symptomes')),
                ('principes_traitements', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Principes de traitements')),
                ('points_acu', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Points acupuncture')),
                ('plantes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Plantes')),
                ('prescriptions', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Prescriptions')),
            ],
        ),
        migrations.AlterModelOptions(
            name='planteprescriptionjingfang',
            options={'verbose_name': 'Jing Fang Zhang Zhong Jing', 'verbose_name_plural': 'Jing Fang Zhang Zhong Jing'},
        ),
        migrations.AlterModelOptions(
            name='planteprescriptionzangfuqui',
            options={'verbose_name': 'Jing Fang Feng Shi Lun', 'verbose_name_plural': 'Jing Fang Feng Shi Lun'},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='remarques',
            field=models.TextField(default='', max_length=2000, verbose_name='Effets thérapeutiques'),
        ),
    ]
