# Generated by Django 4.0.6 on 2022-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0011_alter_diagnostic_causes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='symptomes_explications',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Symptomes'),
        ),
    ]
