# Generated by Django 4.0.6 on 2022-08-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0012_alter_diagnostic_symptomes_explications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='symptomes_explications',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Symptomes'),
        ),
    ]
