# Generated by Django 4.0.6 on 2022-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0014_contact_test_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='test',
        ),
        migrations.AddField(
            model_name='contact',
            name='adresse',
            field=models.CharField(max_length=200, null=True, verbose_name='ADRESSE POSTALE <br>(complète (pour livraison))'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cp',
            field=models.CharField(max_length=200, null=True, verbose_name='CODE POSTAL'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_naissance',
            field=models.CharField(max_length=200, null=True, verbose_name='DATE de naissance'),
        ),
        migrations.AddField(
            model_name='contact',
            name='lieu_naissance',
            field=models.CharField(max_length=200, null=True, verbose_name='LIEU de naissance'),
        ),
        migrations.AddField(
            model_name='contact',
            name='nb_enfants',
            field=models.CharField(max_length=200, null=True, verbose_name='ENFANTS (nombres)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=200, null=True, verbose_name='NOM'),
        ),
        migrations.AddField(
            model_name='contact',
            name='portable',
            field=models.CharField(max_length=200, null=True, verbose_name='PORTABLE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=200, null=True, verbose_name='PRENOM'),
        ),
        migrations.AddField(
            model_name='contact',
            name='recommande_par',
            field=models.CharField(max_length=200, null=True, verbose_name='RECOMMANDÉ PAR'),
        ),
        migrations.AddField(
            model_name='contact',
            name='situation_familiale',
            field=models.CharField(max_length=200, null=True, verbose_name='SITUATION FAMILIALE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ville',
            field=models.CharField(max_length=200, null=True, verbose_name='VILLE'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='COURRIEL'),
        ),
    ]
