# Generated by Django 4.0.6 on 2022-08-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0015_remove_contact_firstname_remove_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vous_ne_transpirez_jamais',
            field=models.BooleanField(max_length=5, null=True, verbose_name='Vous ne transpirez jamais, ou pratiquement jamais ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=models.CharField(max_length=200, null=True, verbose_name='ADRESSE POSTALE'),
        ),
    ]
