# Generated by Django 4.0.6 on 2022-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0023_rename_vous_ne_transpirez_jamais_contact_vous_ne_transpirez_jamais_ou_pratiqueme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='LES_COURANTS_DAIR_LE_VENT',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LE_CHAUD',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LE_FROID',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LHUMIDITe',
        ),
        migrations.AddField(
            model_name='contact',
            name='AVEZ_VOUS_DES_ADDICTIONS',
            field=models.BooleanField(default=False, verbose_name='AVEZ-VOUS DES ADDICTIONS'),
        ),
        migrations.AddField(
            model_name='contact',
            name='A_des_aliments',
            field=models.BooleanField(default=False, verbose_name='A des aliments ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='A_des_medicaments',
            field=models.BooleanField(default=False, verbose_name='A des médicaments ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Aimez_vous_la_chaleur_sur_labdomen',
            field=models.BooleanField(default=False, verbose_name='Aimez-vous la chaleur sur l’abdomen ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Allez_vous_chaque_jour_a_la_selle',
            field=models.BooleanField(default=False, verbose_name='Allez-vous chaque jour à la selle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Allez_vous_plusieurs_fois_par_jour_a_la',
            field=models.BooleanField(default=False, verbose_name='Allez-vous plusieurs fois par jour à la selle ? Combien ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Apres_les_regles_etes_vous_fatiguee',
            field=models.BooleanField(default=False, verbose_name='Après les règles êtes-vous fatiguée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Au_niveau_de_la_TeTE',
            field=models.BooleanField(default=False, verbose_name='Au niveau de la TÊTE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_dans_la_bouche_un_autre_gout_a',
            field=models.BooleanField(default=False, verbose_name='Avez-vous dans la bouche un autre goût anormal ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_dans_la_bouche_un_gout_amer',
            field=models.BooleanField(default=False, verbose_name='Avez-vous dans la bouche un goût amer ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_dans_la_bouche_un_gout_metalli',
            field=models.BooleanField(default=False, verbose_name='Avez-vous dans la bouche un goût métallique ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_de_la_diarrhee',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous de la diarrhée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_de_la_fievre_de_la_soif_etes',
            field=models.BooleanField(default=False, verbose_name='Avez-vous de la fièvre, de la soif, êtes-vous agité, transpirez-vous ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_de_la_fievre_en_fin_dapres_mi',
            field=models.BooleanField(default=False, verbose_name='Avez-vous de la fièvre en fin d’après-midi ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_de_la_toux',
            field=models.BooleanField(default=False, verbose_name='Avez-vous de la toux ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_de_lirritabilite_de_la_col',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous de l’irritabilité, de la colère, de la nervosité ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_MAUX_DE_TeTE',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des MAUX DE TÊTE ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_acouphenes',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des acouphènes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_acouphenes_des_vertiges',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des acouphènes, des vertiges, la gorge et la bouche sèches ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_borborygmes',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des borborygmes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_borborygmes_bruits_au',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des borborygmes (bruits) au niveau de l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_caillots_dans_vos_regles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des caillots dans vos règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_coups_de_barre_A_quelles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des coups de barre ? A quelles heures ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_courbatures_generalisees',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des courbatures généralisées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_crampes',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des crampes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_APReS_les_regles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs APRÈS les règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_AVANT_les_regles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs AVANT les règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_PENDANT_les_regle',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs PENDANT les règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_au_BAS_DU_DOS',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs au BAS DU DOS ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_au_VENTRE',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs au VENTRE ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_au_moment_de_lov',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs au moment de l’ovulation ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_aux_SEINS',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs aux SEINS ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_douleurs_liees_aux_regles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des douleurs liées aux règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_engourdissements',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des engourdissements ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_eructations_et_hoquets_f',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des éructations et hoquets fréquents ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_eructations_fetides_ou_q',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des éructations fétides ou qui ont de l’odeur d’aliments ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_eternuements',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des éternuements ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_etourdissements_peu_ou_pa',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des étourdissements, peu ou pas faim, des insomnies, des palpitations cardiaques, des rêves abondants, les lèvres pâles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_fringales_de_sucre',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des fringales de sucré ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_gaz',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des gaz ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_hemorragies_uterine_en_DEH',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des hémorragies utérine en DEHORS des règles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_infections',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des infections ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_levres_seches_brulees_o',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des lèvres sèches, brulées ou fissurées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_maux_de_tete_ou_cephalee',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des maux de tête (ou céphalée) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_migraines_un_seul_et_meme',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des migraines (un seul et même coté du crâne) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_mucosites_gorge_nez_bou',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des mucosités (gorge, nez, bouche, palais) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_myalgies_douleur_dans_les',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des myalgies (douleur dans les muscles) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_mycoses',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des mycoses ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_palpitations_cardiaques',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des palpitations cardiaques ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_pertes_leucorrhees',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des pertes (leucorrhées) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_raideurs_musculaires',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des raideurs musculaires ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_regurgitacions_acides',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des régurgitacions acides ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_rots',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des rots ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_selles_molles',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des selles molles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_sensations_de_fourmillemen',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des sensations de fourmillement, de picotements, d’engourdissement ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_spasmes',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des spasmes ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_spasmes_musculaires_tendi',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des spasmes musculaires, tendineux ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_tendinites',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des tendinites ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_tics_des_tremblements',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des tics, des tremblements ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_traces_daliments_non_di',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des traces d’aliments non digérés dans les selles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_vertiges',
            field=models.BooleanField(default=False, verbose_name='Avez-vous des vertiges ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_des_vomissements_daliments',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous des vomissements d’aliments non digérés ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_en_meme_temps_de_la_fievre_et',
            field=models.BooleanField(default=False, verbose_name='Avez-vous en même temps de la fièvre et des frissons ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_faim_sans_desir_de_manger',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous faim sans désir de manger ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_frequemment_des_eructations',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous fréquemment des éructations ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_frequemment_des_hoquets',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous fréquemment des hoquets ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_la_langue_et_la_gorge_seche',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous la langue et la gorge sèche ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_la_partie_abdominale_au_dessus',
            field=models.BooleanField(default=False, verbose_name='Avez-vous la partie abdominale au dessus du nombril, gonflée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_la_partie_abdominale_en_dessou',
            field=models.BooleanField(default=False, verbose_name='Avez-vous la partie abdominale en dessous du nombril, gonflée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_la_tete_lourde',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous la tête lourde ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_labdomen_dans_son_ensemble_g',
            field=models.BooleanField(default=False, verbose_name='Avez-vous l’abdomen dans son ensemble, gonflé, DUR, sensible à la pression ?   '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_nez_bouche',
            field=models.BooleanField(default=False, verbose_name='Avez-vous le nez bouché ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_nez_qui_coule',
            field=models.BooleanField(default=False, verbose_name='Avez-vous le nez qui coule ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_plexus_solaire_tendu_voire',
            field=models.BooleanField(default=False, verbose_name='Avez-vous le plexus solaire tendu, voire sensible ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_sentiment_davoir_perdu_l',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous le sentiment d’avoir perdu le goût des aliments ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_teint_pale_ou_la_langue_p',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous le teint pâle ou la langue pâle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_le_teint_pâle_terne',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous le teint pâle, terne ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_les_levres_pâles',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous les lèvres pâles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_les_selles_liquides_et_peu_o',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous les selles liquides et peu odorantes ou du sang dans les selles ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_les_selles_seches',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous les selles sèches ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_mauvaise_haleine',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous mauvaise haleine ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_parfois_des_ballonnements',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous parfois des ballonnements ? Des borborygmes ? Des flatulences ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_parfois_des_nausees',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous parfois des nausées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_parfois_la_bouche_pâteuse',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous parfois la bouche pâteuse ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_perdu_de_la_force_musculaire',
            field=models.BooleanField(default=False, verbose_name='Avez-vous perdu de la force musculaire ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_perdu_la_mobilite_dune_ou_plu',
            field=models.BooleanField(default=False, verbose_name='Avez-vous perdu la mobilité d’une ou plusieurs articulations ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_perdu_le_gout',
            field=models.BooleanField(default=False, verbose_name='Avez-vous perdu le goût'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_perdu_lodorat',
            field=models.BooleanField(default=False, verbose_name='Avez-vous perdu l’odorat ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_souvent_faim_et_un_fort_appe',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous souvent faim et un fort appétit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_tandance_a_etre_facilement_rev',
            field=models.BooleanField(default=False, verbose_name='Avez-vous tendance à être facilement réveillé ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_degout_pour_la_nourriture',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous un dégoût pour la nourriture ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_moyen_de_contraception_chim',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un moyen de contraception chimique (pilule) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_moyen_de_contraception_mixt',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un moyen de contraception mixte ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_moyen_de_contraception_uniq',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un moyen de contraception uniquement mécanique ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_syndrome_premenstruel',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous un syndrome prémenstruel ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_un_traitement_hormonal',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un traitement hormonal ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_absence_de_flux_menstruel',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une absence de flux menstruel en dehors de la grossesse ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_digestion_lente',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une digestion lente ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_digestion_rapide',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une digestion rapide ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_digestion_tres_lourde_et',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une digestion très lourde et longue ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_diminution_de_lappetit',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une diminution de l’appétit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_distension_et_une_douleu',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une distension et une douleur de l’estomac avec élancement vers les hypocondres ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_douleur_de_lestomac_acc',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une douleur de l’estomac accompagnée de sensation de distension, de froid et de plénitude ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_gene_ou_de_la_difficulte_a',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une gène ou de la difficulté à respirer ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_mauvaise_haleine',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une mauvaise haleine ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_sensation_de_chaleur_local',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une sensation de chaleur locale, de la rougeur locale ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_sensation_de_froid_dans',
            field=models.BooleanField(default=False, verbose_name='• Avez-vous une sensation de froid dans l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_sensation_de_froid_dans_la',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une sensation de froid dans la partie atteinte sans que cela ne soit froid au toucher ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_une_sensation_de_froid_dans_le',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une sensation de froid dans le petit bassin améliorée par la chaleur ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='CARACTERISTIQUES_DE_VOS_DOULEURS',
            field=models.BooleanField(default=False, verbose_name='CARACTERISTIQUES DE VOS DOULEURS :                                                voir et remplir le questionnaire spécifique (Q7) pour bien décrire vos douleurs'),
        ),
        migrations.AddField(
            model_name='contact',
            name='CE_QUI_AUGMENTE_VOS_DOULEUR',
            field=models.BooleanField(default=False, verbose_name='CE QUI AUGMENTE VOS DOULEUR : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='CE_QUI_CALME_VOS_DOULEUR',
            field=models.BooleanField(default=False, verbose_name='CE QUI CALME VOS DOULEUR : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Cafe',
            field=models.BooleanField(default=False, verbose_name='Café ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ce_sont_surtout_la_region_lombaire',
            field=models.BooleanField(default=False, verbose_name='Ce sont surtout la région lombaire («\xa0les reins\xa0») qui est touchée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ce_sont_surtout_les_genoux_qui_sont_touc',
            field=models.BooleanField(default=False, verbose_name='Ce sont surtout les genoux qui sont touchés ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ce_sont_surtout_les_hanches_qui_sont_tou',
            field=models.BooleanField(default=False, verbose_name='Ce sont surtout les hanches qui sont touchés ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Certaines_parties_de_votre_peau_vous_dem',
            field=models.BooleanField(default=False, verbose_name='Certaines parties de votre peau vous démangent-elles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Cette_douleur_est_elle_aggravee_par_le',
            field=models.BooleanField(default=False, verbose_name='• Cette douleur est-elle aggravée par le froid et améliorée par la chaleur ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Combien_de_fois_la_nuit',
            field=models.BooleanField(default=False, verbose_name='Combien de fois la nuit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Combien_de_pulsations_cardiaques_avez_vo',
            field=models.BooleanField(default=False, verbose_name='Combien de pulsations cardiaques avez-vous en une minute, au repos ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Comment_les_traitez_vous',
            field=models.BooleanField(default=False, verbose_name='Comment les traitez-vous ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Commentaires',
            field=models.BooleanField(default=False, verbose_name='Commentaires : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Craignez_vous_le_froid',
            field=models.BooleanField(default=False, verbose_name='Craignez-vous le froid ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Craignez_vous_le_froid_ou_avez_vous_le',
            field=models.BooleanField(default=False, verbose_name='• Craignez-vous le froid ou avez-vous le nez et les mains froids ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='De_contact',
            field=models.BooleanField(default=False, verbose_name='De contact ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Detestez_vous_le_vent_les_courants_dai',
            field=models.BooleanField(default=False, verbose_name='Détestez-vous le vent, les courants d’air ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Drogue',
            field=models.BooleanField(default=False, verbose_name='Drogue ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Eprouvez_vous_le_besoin_de_bailler_ou',
            field=models.BooleanField(default=False, verbose_name='• Eprouvez-vous le besoin de bailler ou de vous étirer souvent ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Est_ce_que_lenduit_de_votre_langue_a',
            field=models.BooleanField(default=False, verbose_name='• Est-ce que l’enduit de votre langue a un aspect gras, sale, trouble ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Est_ce_que_vos_troubles_digestifs_sont',
            field=models.BooleanField(default=False, verbose_name='• Est-ce que vos troubles digestifs sont aggravés par les émotions et le stress ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Etes_vous_constipe',
            field=models.BooleanField(default=False, verbose_name='• Etes-vous constipé ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Etes_vous_fatigue',
            field=models.BooleanField(default=False, verbose_name='Etes-vous fatigué ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Etes_vous_plutot_attire_par_des_boisso',
            field=models.BooleanField(default=False, verbose_name='• Etes-vous plutôt attiré par des boissons fraiches ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Faites_vous_des_cauchemars',
            field=models.BooleanField(default=False, verbose_name='Faites-vous des cauchemars ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Faites_vous_des_reves_perturbant_votre_s',
            field=models.BooleanField(default=False, verbose_name='Faites-vous des rêves perturbant votre sommeil ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Globalement_dans_toutes_les_articulation',
            field=models.BooleanField(default=False, verbose_name='Globalement dans toutes les articulations ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Il_y_a_du_sang_dans_vos_selles',
            field=models.BooleanField(default=False, verbose_name='Il y a du sang dans vos selles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='LETATS_DES_VOS_ARTICULATIONS_ACTUELLEME',
            field=models.BooleanField(default=False, verbose_name='L’ETATS DES VOS ARTICULATIONS ACTUELLEMENT :'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_DUReE_de_vos_regles',
            field=models.BooleanField(default=False, verbose_name='La DURÉE de vos règles'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_QUANTITe_de_sang_ecoule',
            field=models.BooleanField(default=False, verbose_name='La QUANTITÉ de sang écoulé'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_demangeaison_est_elle_insupportable',
            field=models.BooleanField(default=False, verbose_name='La démangeaison est-elle insupportable ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_aggravee_la_nuit',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle aggravée la nuit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_aggravee_par_la_chal',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle aggravée par la chaleur et le massage ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_aggravee_par_le_froi',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle aggravée par le froid, l’effort ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_aggravee_par_le_mouv',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle aggravée par le mouvement ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_amelioree_par_le_fro',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle améliorée par le froid ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_localisee_avec_une',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle localisée, avec une sensation de lourdeur, d’engourdissement, d’endolorissement ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_mobile_changeante',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle mobile, changeante, elle va et vient d’un endroit à un autre, elle change de zone, ou irradie vers une zone éloignée ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_peu_severe_mais_chro',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle peu sévère mais chronique ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_peu_violente_mais_pe',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle peu violente mais persistante ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_severe_avec_une_sen',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle sévère, avec une sensation de chaleur, de rougeur locale avec tuméfaction ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_douleur_est_elle_severe_fixe_locali',
            field=models.BooleanField(default=False, verbose_name='La douleur est-elle sévère, fixe, localisée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_mobilite_des_articulations_est_elle_l',
            field=models.BooleanField(default=False, verbose_name='La mobilité des articulations est-elle limitée et améliorée par la chaleur et le massage ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_nuque_le_cou_le_rachis_cervical',
            field=models.BooleanField(default=False, verbose_name='La nuque, le cou, le rachis cervical ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_ou_cela_vous_demange_cela_est_il_cha',
            field=models.BooleanField(default=False, verbose_name='Là où cela vous démange, cela est-il chaud ou cela brule-t-il (avant de se gratter) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_ou_cela_vous_demange_cela_est_il_rou',
            field=models.BooleanField(default=False, verbose_name='Là où cela vous démange, cela est-il rouge (avant de gratter) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_ou_cela_vous_demange_cela_suinte_t_i',
            field=models.BooleanField(default=False, verbose_name='Là où cela vous démange, cela suinte-t-il ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_ou_cela_vous_demange_y_a_t_il_des_cl',
            field=models.BooleanField(default=False, verbose_name='Là où cela vous démange, y a-t-il des cloques avec un liquide coloré ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_poitrine',
            field=models.BooleanField(default=False, verbose_name='La poitrine ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_pression_le_massage',
            field=models.BooleanField(default=False, verbose_name='La pression, le massage ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_quantite_de_sang_vous_semble_t_elle_n',
            field=models.BooleanField(default=False, verbose_name='La quantité de sang vous semble-t-elle normales ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='La_tete',
            field=models.BooleanField(default=False, verbose_name='La tête ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Labdomen',
            field=models.BooleanField(default=False, verbose_name='L’abdomen ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_bas_du_dos_rachis_lombaire',
            field=models.BooleanField(default=False, verbose_name='Le bas du dos (rachis lombaire) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_chaud',
            field=models.BooleanField(default=False, verbose_name='Le chaud ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_froid',
            field=models.BooleanField(default=False, verbose_name='Le froid ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_froid_ou_lhumidite_augmentent_ils_la',
            field=models.BooleanField(default=False, verbose_name='Le froid ou l’humidité augmentent-ils la douleur ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_haut_du_dos',
            field=models.BooleanField(default=False, verbose_name='Le haut du dos ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_milieu_du_dos',
            field=models.BooleanField(default=False, verbose_name='Le milieu du dos ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_mouvement',
            field=models.BooleanField(default=False, verbose_name='Le mouvement ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Le_nez',
            field=models.BooleanField(default=False, verbose_name='Le nez ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Lequel',
            field=models.BooleanField(default=False, verbose_name='Lequel ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_aliments_ne_sont_ils_pas_digeres',
            field=models.BooleanField(default=False, verbose_name='Les aliments ne sont-ils pas digérés ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_douloureuses_sont_chau',
            field=models.BooleanField(default=False, verbose_name='Les articulations douloureuses sont chaudes'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_douloureuses_sont_enfl',
            field=models.BooleanField(default=False, verbose_name='Les articulations douloureuses sont enflées'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_douloureuses_sont_froi',
            field=models.BooleanField(default=False, verbose_name='Les articulations douloureuses sont froides'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_douloureuses_sont_roug',
            field=models.BooleanField(default=False, verbose_name='Les articulations douloureuses sont rouges'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_ont_elles_des_oedemes',
            field=models.BooleanField(default=False, verbose_name='Les articulations ont-elles des oedèmes, sont-elles enflées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_ont_elles_perdues_de_l',
            field=models.BooleanField(default=False, verbose_name='Les articulations ont-elles perdues de l’amplitude dans leurs mouvements, sont-elles limitées avec des engourdissements, des douleurs ?   '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_articulations_sont_elles_douloureuse',
            field=models.BooleanField(default=False, verbose_name='Les articulations sont-elles douloureuses, raides, déformées, froides ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_chevilles',
            field=models.BooleanField(default=False, verbose_name='Les chevilles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_cotes',
            field=models.BooleanField(default=False, verbose_name='Les cotes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_douleurs_sont_elles_surtout_situees',
            field=models.BooleanField(default=False, verbose_name='Les douleurs, sont-elles surtout situées aux membres inférieurs ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_epaules',
            field=models.BooleanField(default=False, verbose_name='Les épaules ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_genoux',
            field=models.BooleanField(default=False, verbose_name='Les genoux ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_hanches',
            field=models.BooleanField(default=False, verbose_name='Les hanches ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_oreilles',
            field=models.BooleanField(default=False, verbose_name='Les oreilles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_pieds',
            field=models.BooleanField(default=False, verbose_name='Les pieds ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_trapezes_entre_le_cou_et_les_epaule',
            field=models.BooleanField(default=False, verbose_name='Les trapèzes (entre le cou et les épaules) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Les_yeux',
            field=models.BooleanField(default=False, verbose_name='Les yeux ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Lesquels',
            field=models.BooleanField(default=False, verbose_name='Lesquels ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Manquez_vous_dappetit',
            field=models.BooleanField(default=False, verbose_name='• Manquez-vous d’appétit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Medicaments',
            field=models.BooleanField(default=False, verbose_name='Médicaments ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Par_de_la_chaleur_bouillotte_ou_autre',
            field=models.BooleanField(default=False, verbose_name='Par de la chaleur (bouillotte ou autre)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Par_des_medicaments',
            field=models.BooleanField(default=False, verbose_name='Par des médicaments'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Preferez_vous_boire_chaud',
            field=models.BooleanField(default=False, verbose_name='• Préférez-vous boire chaud ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Prenez_vous_facilement_du_poids',
            field=models.BooleanField(default=False, verbose_name='• Prenez-vous facilement du poids ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Respiratoires',
            field=models.BooleanField(default=False, verbose_name='Respiratoires ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ressentez_vous_une_oppression_au_niveau',
            field=models.BooleanField(default=False, verbose_name='Ressentez-vous une oppression au niveau des régions thoraciques latérales ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ressentez_vous_une_oppression_thoracique',
            field=models.BooleanField(default=False, verbose_name='Ressentez-vous une oppression thoracique ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sale',
            field=models.BooleanField(default=False, verbose_name='Salé ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sensation_dans_la_BOUCHE',
            field=models.BooleanField(default=False, verbose_name='Sensation dans la BOUCHE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sodas',
            field=models.BooleanField(default=False, verbose_name='Sodas ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sont_elles_blanchâtres',
            field=models.BooleanField(default=False, verbose_name='Sont-elles blanchâtres ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sont_elles_plutôt_jaunes_ordorantes',
            field=models.BooleanField(default=False, verbose_name='Sont-elles plutôt jaunes, ordorantes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sont_elles_striees_de_sang',
            field=models.BooleanField(default=False, verbose_name='Sont-elles striées de sang ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sont_elles_translucides_comme_du_blanc_d',
            field=models.BooleanField(default=False, verbose_name='Sont-elles translucides comme du blanc d’oeuf cru ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_douleurs_a_lestomac',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de douleurs à l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_gingivite',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de gingivite ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_sensation_de_douleur',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de sensation de douleur et/ou de gonflement et/ou d’oppression sur au moins l’une des zones suivantes : poitrine, hypochondre, abdomen, petit bassin ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_sensations_de_brulure',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de sensations de brulures dans l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_somnolence_dhypersomn',
            field=models.BooleanField(default=False, verbose_name='Souffrez-vous de somnolence, d’hypersomnie ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_transpiration_nocturn',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de transpiration nocturne ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_de_vomissements_de_liqui',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous de vomissements de liquides clairs ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_dinsomnies',
            field=models.BooleanField(default=False, verbose_name='Souffrez-vous d’insomnies ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_doedemes',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous d’oedèmes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_dun_etat_depressif',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous d’un état dépressif ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_dune_colopathie_fonctio',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous d’une colopathie fonctionnelle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Souffrez_vous_dune_sensation_de_gene',
            field=models.BooleanField(default=False, verbose_name='• Souffrez-vous d’une sensation de gène, de malaise, de faim dans l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Soufrez_vous_de_douleur_legere_sourde',
            field=models.BooleanField(default=False, verbose_name='• Soufrez-vous de douleur légère, sourde de l’estomac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Soupirez_vous_souvent',
            field=models.BooleanField(default=False, verbose_name='• Soupirez-vous souvent ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Stagnation_aliments_dans_Wei',
            field=models.BooleanField(default=False, verbose_name='Stagnation aliments dans Wei =2X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sucre',
            field=models.BooleanField(default=False, verbose_name='Sucré ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Tabac',
            field=models.BooleanField(default=False, verbose_name='Tabac ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='The',
            field=models.BooleanField(default=False, verbose_name='Thé ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Tous_les_combien_de_jours_y_allez_vous',
            field=models.BooleanField(default=False, verbose_name='Tous les combien de jours y allez-vous ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Urinez_vous_la_nuit',
            field=models.BooleanField(default=False, verbose_name='Urinez-vous la nuit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Urinez_vous_souvent_abondamment_et_de_c',
            field=models.BooleanField(default=False, verbose_name='Urinez-vous souvent, abondamment et de couleur pâle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vomissez_vous_parfois',
            field=models.BooleanField(default=False, verbose_name='• Vomissez-vous parfois ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_articulations_sont_elles_deformees_a',
            field=models.BooleanField(default=False, verbose_name='Vos articulations sont-elles déformées avec une perte de mobilité ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_articulations_sont_elles_douloureuse',
            field=models.BooleanField(default=False, verbose_name='Vos articulations sont-elles douloureuses, contractées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_douleurs_ressemblent_elles_a_des_cou',
            field=models.BooleanField(default=False, verbose_name='Vos douleurs ressemblent-elles à des coups d’aiguille ou de couteau ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_douleurs_ressemblent_elles_a_une_pre',
            field=models.BooleanField(default=False, verbose_name='Vos douleurs ressemblent-elles à une pression, un gonflement douloureux ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_douleurs_sont_elles_sourdes',
            field=models.BooleanField(default=False, verbose_name='Vos douleurs sont-elles sourdes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_membres_sont_ils_froids',
            field=models.BooleanField(default=False, verbose_name='Vos membres sont-ils froids ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_durent_elles_7_jours_et_plus',
            field=models.BooleanField(default=False, verbose_name='Vos règles durent-elles 7 jours et plus ?                                                           (du tout début à la toute fin des saignements)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_durent_elles_au_maximum_3_jou',
            field=models.BooleanField(default=False, verbose_name='Vos règles durent-elles au maximum 3 jours ?                                                       (du tout début à la toute fin des saignements) '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_durent_elles_entre_4_a_6_jour',
            field=models.BooleanField(default=False, verbose_name='Vos règles durent-elles entre 4 à 6 jours ?                                                             (du tout début à la toute fin des saignements) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_sont_elles_abondantes',
            field=models.BooleanField(default=False, verbose_name='Vos règles sont-elles abondantes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_sont_elles_hemorragiques',
            field=models.BooleanField(default=False, verbose_name='Vos règles sont-elles hémorragiques ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_regles_sont_elles_peu_abondantes',
            field=models.BooleanField(default=False, verbose_name='Vos règles sont-elles peu abondantes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sentent_elles_excessivement_f',
            field=models.BooleanField(default=False, verbose_name='Vos selles sentent-elles excessivement fort, c’est une puanteur ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_abondantes',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles abondantes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_defaites',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles défaites ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_douloureuses',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles douloureuses ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_dures',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles dures ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_liquides',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles liquides ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_molles',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles molles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_peu_abondantes',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles peu abondantes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_seches',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles sèches ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_selles_sont_elles_seches_comme_des_b',
            field=models.BooleanField(default=False, verbose_name='Vos selles sont-elles sèches comme des billes dures ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_sensations_au_niveau_de_LA_PEAU',
            field=models.BooleanField(default=False, verbose_name='Vos sensations au niveau de LA PEAU'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_sensations_au_niveau_des_MUSCLES',
            field=models.BooleanField(default=False, verbose_name='Vos sensations au niveau des MUSCLES'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_ont_elles_une_odeur',
            field=models.BooleanField(default=False, verbose_name='Vos urines ont-elles une odeur ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_claires',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles claires ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_difficiles_a_evacu',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles difficiles à évacuer ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_en_grandes_quantit',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles en grandes quantité à chaque fois ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_en_petite_quantite',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles en petite quantité à chaque fois ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_foncees',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles foncées ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_frequentes',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles fréquentes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_nombreuses',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles nombreuses ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vos_urines_sont_elles_troubles',
            field=models.BooleanField(default=False, verbose_name='Vos urines sont-elles troubles ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_articulation_douloureuse_bouge',
            field=models.BooleanField(default=False, verbose_name='Votre articulation douloureuse bouge-t-elle moins bien ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_cycle_est_il_irregulier',
            field=models.BooleanField(default=False, verbose_name='Votre cycle est-il irrégulier ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_cycle_est_il_quelques_fois_court_e',
            field=models.BooleanField(default=False, verbose_name='Votre cycle est-il quelques fois court et quelques fois long ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_cycle_est_il_regulier',
            field=models.BooleanField(default=False, verbose_name='Votre cycle est-il régulier (28/29j ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_cycle_est_il_toujours_court_moins',
            field=models.BooleanField(default=False, verbose_name='Votre cycle est-il toujours court (moins de 28 jours) ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_cycle_est_toujours_long_plus_de_2',
            field=models.BooleanField(default=False, verbose_name='Votre cycle est toujours long (plus de 29 jours) ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_douleur_est_elle_aggravee_a_la_pre',
            field=models.BooleanField(default=False, verbose_name='Votre douleur est-elle aggravée à la pression et a-t-elle la forme d’un clou, très ponctuelle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_fatigue_ou_la_situez_vous',
            field=models.BooleanField(default=False, verbose_name='Votre fatigue, où la situez-vous ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_collant_gluant',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il collant, gluant ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_epais',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il épais ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_pourpre',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il pourpre ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_rose_pâle',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il rose pâle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_rouge_vif',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il rouge vif ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_sombre',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il sombre ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_tres_clair',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il très clair ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Votre_sang_est_il_tres_liquide_tres_flu',
            field=models.BooleanField(default=False, verbose_name='Votre sang est-il très liquide, très fluide ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_mettez_vous_souvent_en_colere_et',
            field=models.BooleanField(default=False, verbose_name='• Vous mettez-vous souvent en colère, êtes-vous irritable ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_navez_pas_de_moyen_de_contraceptio',
            field=models.BooleanField(default=False, verbose_name='Vous n’avez pas de moyen de contraception ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_ne_faites_rien_et_attendez_que_cela',
            field=models.BooleanField(default=False, verbose_name='Vous ne faites rien et attendez que cela passe'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_ne_supportez_pas_la_chaleur_sur_la',
            field=models.BooleanField(default=False, verbose_name='Vous ne supportez pas la chaleur sur l’abdomen ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_sentez_vous_epuise_au_point_de_dev',
            field=models.BooleanField(default=False, verbose_name='Vous sentez-vous épuisé, au point de devoir dormir, en ce moment ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_sentez_vous_fatigue_avez_vous_le_s',
            field=models.BooleanField(default=False, verbose_name='Vous sentez-vous fatigué, avez-vous le souffle court, transpirez-vous spontanément ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_sentez_vous_fatigue_en_ce_moment',
            field=models.BooleanField(default=False, verbose_name='Vous sentez-vous fatigué en ce moment ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_sentez_vous_tres_souvent_epuise_au',
            field=models.BooleanField(default=False, verbose_name='Vous sentez-vous très souvent épuisé, au point de devoir dormir ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Vous_sentez_vous_tres_souvent_fatigue',
            field=models.BooleanField(default=False, verbose_name='Vous sentez-vous très souvent fatigué ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Y_a_t_il_de_la_rougeur_une_sensation_de',
            field=models.BooleanField(default=False, verbose_name='Y a-t-il de la rougeur, une sensation de chaleur locale ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Y_a_t_il_une_rougeur_locale',
            field=models.BooleanField(default=False, verbose_name='Y a-t-il une rougeur locale ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_menopausee',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous ménopausée ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_souvent_fatigue_apres_le_rep',
            field=models.BooleanField(default=False, verbose_name='• Êtes-vous souvent fatigué après le repas ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='la_bouche',
            field=models.BooleanField(default=False, verbose_name='la bouche ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='les_coudes',
            field=models.BooleanField(default=False, verbose_name='les coudes ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='les_poignets_mains_doigts',
            field=models.BooleanField(default=False, verbose_name='les poignets, mains, doigts ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Transpirez_vous_la_nuit',
            field=models.BooleanField(default=False, verbose_name='Transpirez-vous la nuit ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Vous_avez_chaud_quand_il_fait_chaud_et',
            field=models.BooleanField(default=False, verbose_name='Vous avez chaud quand il fait chaud, et avez froid quand il fait froid'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Vous_vous_forcez_de_boire_15l_deau_par',
            field=models.BooleanField(default=False, verbose_name='Vous vous forcez de boire 1,5l deau par jour parce que vous pensez que cest bon pour votre organisme'),
        ),
    ]
