# Generated by Django 4.0.6 on 2022-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0024_remove_contact_les_courants_dair_le_vent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='La_pression_le_massage',
            new_name='augmente_douleur_La_pression_le_massage',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Le_chaud',
            new_name='augmente_douleur_Le_chaud',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Le_froid',
            new_name='augmente_douleur_Le_froid',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Le_mouvement',
            new_name='augmente_douleur_Le_mouvement',
        ),
        migrations.AddField(
            model_name='contact',
            name='LES_COURANTS_DAIR_LE_VENT',
            field=models.BooleanField(default=False, verbose_name='LES COURANTS DAIR _ LE VENT'),
        ),
        migrations.AddField(
            model_name='contact',
            name='LE_FROID',
            field=models.BooleanField(default=False, verbose_name='LE FROID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='augmente_douleur_La_nuit',
            field=models.BooleanField(default=False, verbose_name='La nuit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='augmente_douleur_Le_jour',
            field=models.BooleanField(default=False, verbose_name='Le jour ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_La_nuit',
            field=models.BooleanField(default=False, verbose_name='La nuit ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_La_pression_le_massage',
            field=models.BooleanField(default=False, verbose_name='La pression, le massage ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_Le_chaud',
            field=models.BooleanField(default=False, verbose_name='Le chaud ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_Le_froid',
            field=models.BooleanField(default=False, verbose_name='Le froid ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_Le_jour',
            field=models.BooleanField(default=False, verbose_name='Le jour ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='calme_douleur_Le_mouvement',
            field=models.BooleanField(default=False, verbose_name='Le mouvement ?'),
        ),
    ]
