# Generated by Django 4.0.6 on 2022-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0026_alter_contact_les_courants_dair_le_vent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='_mefA',
            field=models.CharField(max_length=200, null=True, verbose_name='Questionnaire n°2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mefB',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0».'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mefC',
            field=models.CharField(max_length=200, null=True, verbose_name='A propos de vos DOULEURS'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mefD',
            field=models.CharField(max_length=200, null=True, verbose_name='LIEUX DES DOULEURS ?'),
        ),
    ]
