# Generated by Django 4.0.6 on 2022-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0027_contact__mefa_contact__mefb_contact__mefc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='_mefA',
            new_name='_mef17',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='_mefB',
            new_name='_mef18',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='_mefC',
            new_name='_mef19',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='_mefD',
            new_name='_mef20',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='AVEZ_VOUS_DES_ADDICTIONS',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Au_niveau_de_la_TeTE',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Avez_vous_une_sensation_de_SeCHERESSE',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CARACTERISTIQUES_DE_VOS_DOULEURS',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CE_QUI_AUGMENTE_VOS_DOULEUR',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CE_QUI_CALME_VOS_DOULEUR',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Comment_les_traitez_vous',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LES_COURANTS_DAIR_LE_VENT',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LETATS_DES_VOS_ARTICULATIONS_ACTUELLEME',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LE_FROID',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='La_DUReE_de_vos_regles',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='La_QUANTITe_de_sang_ecoule',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='SENSATION_ALTERNeE_DE_CHAUD_ET_DE_FROID',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='SENSATION_DE_CHALEUR',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='SENSATION_DE_FROID',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Sensation_dans_la_BOUCHE',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Stagnation_aliments_dans_Wei',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Vos_sensations_au_niveau_de_LA_PEAU',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Vos_sensations_au_niveau_des_MUSCLES',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Vos_sensations_corporelles_de_CHALEUR_et',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Vos_sensations_par_rapport_au_temps',
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef1',
            field=models.CharField(max_length=200, null=True, verbose_name='Questionnaire général'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef10',
            field=models.CharField(max_length=200, null=True, verbose_name='Vos sensations corporelles de CHALEUR et de FROID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef11',
            field=models.CharField(max_length=200, null=True, verbose_name='SENSATION DE FROID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef13',
            field=models.CharField(max_length=200, null=True, verbose_name='SENSATION DE CHALEUR'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef14',
            field=models.CharField(max_length=200, null=True, verbose_name='Avez_vous une sensation de SÈCHERESSE : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef15',
            field=models.CharField(max_length=200, null=True, verbose_name='FIEVRE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef16',
            field=models.CharField(max_length=200, null=True, verbose_name='SOIF'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef2',
            field=models.CharField(max_length=200, null=True, verbose_name='Questionnaire n°1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef21',
            field=models.CharField(max_length=200, null=True, verbose_name='CE QUI CALME VOS DOULEUR : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef22',
            field=models.CharField(max_length=200, null=True, verbose_name='CE QUI AUGMENTE VOS DOULEUR : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef23',
            field=models.CharField(max_length=200, null=True, verbose_name='L’ETATS DES VOS ARTICULATIONS ACTUELLEMENT :'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef24',
            field=models.CharField(max_length=200, null=True, verbose_name='CARACTERISTIQUES DE VOS DOULEURS :'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef25',
            field=models.CharField(max_length=200, null=True, verbose_name='voir et remplir le questionnaire spécifique (Q7) pour bien décrire vos douleurs'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef26',
            field=models.CharField(max_length=200, null=True, verbose_name='Vos sensations au niveau de LA PEAU'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef27',
            field=models.CharField(max_length=200, null=True, verbose_name='Vos sensations au niveau des MUSCLES'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef28',
            field=models.CharField(max_length=200, null=True, verbose_name='Au niveau de la TÊTE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef29',
            field=models.CharField(max_length=200, null=True, verbose_name='Sensation dans la BOUCHE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef3',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0» appropriée.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef30',
            field=models.CharField(max_length=200, null=True, verbose_name='Questionnaire n°3'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef31',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0» appropriée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef32',
            field=models.CharField(max_length=200, null=True, verbose_name='THORAX'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef33',
            field=models.CharField(max_length=200, null=True, verbose_name='Pour les questions concernant le thorax, donnez le maximum de précisions dans les commentaires'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef34',
            field=models.CharField(max_length=200, null=True, verbose_name='ABDOMEN'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef35',
            field=models.CharField(max_length=200, null=True, verbose_name='Pour les questions concernant l’abdomen, donnez le maximum de précisions dans les commentaires'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef36',
            field=models.CharField(max_length=200, null=True, verbose_name='URINES'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef37',
            field=models.CharField(max_length=200, null=True, verbose_name='Pour les questions concernant les urines, donnez le maximum de précisions dans les commentaires'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef38',
            field=models.CharField(max_length=200, null=True, verbose_name='SELLES'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef39',
            field=models.CharField(max_length=200, null=True, verbose_name='Pour les questions concernant les selles, donnez le maximum de précisions dans les commentaires'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef4',
            field=models.CharField(max_length=200, null=True, verbose_name='TRANSPIRATION (ou peau moite cela est équivalent en médecine chinoise)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef40',
            field=models.CharField(max_length=200, null=True, verbose_name='Questionnaire n°4'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef41',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0» appropriée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef42',
            field=models.CharField(max_length=200, null=True, verbose_name='VOTRE SOMMEIL :'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef43',
            field=models.CharField(max_length=200, null=True, verbose_name='Trouble caractérisé par un endormissement peu profond favorisant les réveils intempestifs durant la nuit Le temps du sommeil est réduit et le remboursement le rendormissement difficile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef44',
            field=models.CharField(max_length=200, null=True, verbose_name='Trouble caractérisé par la perte partielle (ou parfois totale) du sommeil, ou la difficulté à s’endormir ou la tendance à se réveiller fréquemment et facilement avec difficulté à s’endormir à nouveau Pour être pathologique cela doit se prolonger sur une longue période'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef45',
            field=models.CharField(max_length=200, null=True, verbose_name='Trouble caractérisé par de la somnolence est une envie quasi permanente de dormir Généralement, la durée du sommeil est long et peu après le réveil, le patient ressent le besoin de dormir à nouveau Cela peut aller jusqu’à sans dormir à tout moment de la journée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef46',
            field=models.CharField(max_length=200, null=True, verbose_name='Trouble caractérisé par des rêves ou des cauchemars qui perturbent le sommeil et qui empêchent un repos réparateur Ceci a pour conséquence de produire des étourdissements et de la lassitude dans la journée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef47',
            field=models.CharField(max_length=200, null=True, verbose_name='Rêve éprouvant, effrayant ou angoissant qui agite le sommeil ou qui provoque le réveil Ils doivent être fréquent et perturbant'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef48',
            field=models.CharField(max_length=200, null=True, verbose_name='LA FATIGUE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef49',
            field=models.CharField(max_length=200, null=True, verbose_name='ÊTES-VOUS DES ALLERGIES : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef5',
            field=models.CharField(max_length=200, null=True, verbose_name='Vos sensations par rapport au TEMPS QUIL FAIT'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef50',
            field=models.CharField(max_length=200, null=True, verbose_name='AVEZ-VOUS DES ADDICTIONS'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef51',
            field=models.CharField(max_length=200, null=True, verbose_name='n°5 - GYNECOLOGIE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef52',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0» appropriée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef53',
            field=models.CharField(max_length=200, null=True, verbose_name='DURÉE du CYCLE'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef54',
            field=models.CharField(max_length=200, null=True, verbose_name='La DURÉE de vos règles'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef55',
            field=models.CharField(max_length=200, null=True, verbose_name='La QUANTITÉ de sang écoulé'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef56',
            field=models.CharField(max_length=200, null=True, verbose_name='La COULEUR du sang'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef57',
            field=models.CharField(max_length=200, null=True, verbose_name='L’ASPECT du sang'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef58',
            field=models.CharField(max_length=200, null=True, verbose_name='La DOULEUR'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef59',
            field=models.CharField(max_length=200, null=True, verbose_name='LOCALISATION DE LA DOULEUR '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef6',
            field=models.CharField(max_length=200, null=True, verbose_name="LES COURANTS D'AIR / LE VENT"),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef60',
            field=models.CharField(max_length=200, null=True, verbose_name='DESCRIPTION DE LA DOULEUR'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef61',
            field=models.CharField(max_length=200, null=True, verbose_name='Comment les traitez-vous ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef62',
            field=models.CharField(max_length=200, null=True, verbose_name='AUTRES CAS'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef63',
            field=models.CharField(max_length=200, null=True, verbose_name='n°6 - DIGESTION -'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef64',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0» appropriée'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef65',
            field=models.CharField(max_length=200, null=True, verbose_name='Pi Qi Xu =4X + 1 symptôme clef'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef66',
            field=models.CharField(max_length=200, null=True, verbose_name='Pi Yang Qi Xu =2X (+ 4X du Pi Qi Xu)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef67',
            field=models.CharField(max_length=200, null=True, verbose_name='Dysharmonie Gan / Pi =3X (+ 4X du Pi Qi Xu)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef68',
            field=models.CharField(max_length=200, null=True, verbose_name='Dysfonctionnement Wei =3X '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef69',
            field=models.CharField(max_length=200, null=True, verbose_name='Stagnation aliments dans Wei =2X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef7',
            field=models.CharField(max_length=200, null=True, verbose_name='LE FROID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef70',
            field=models.CharField(max_length=200, null=True, verbose_name='Wei Re =2X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef71',
            field=models.CharField(max_length=200, null=True, verbose_name='Wei Yin Xu =2/3X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef72',
            field=models.CharField(max_length=200, null=True, verbose_name='Wei Han =2X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef73',
            field=models.CharField(max_length=200, null=True, verbose_name='Dysharmonie Gan / Wei =3X (+ 3X du dysfonctionnement Wei)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef74',
            field=models.CharField(max_length=200, null=True, verbose_name='n°7 - Bi - DOULEURS ARTICULAIRES -'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef75',
            field=models.CharField(max_length=200, null=True, verbose_name='Ce questionnaire devrait permettre un bon diagnostic de vos douleurs                                                                          Diagnostic indispensable à un traitement personnalisé et adapté à VOUS           Pour cela, vous devrez analyser le type de douleur que vous avez en répondant à l’ensemble de toutes les questions                                Ne cherchez pas de cohérence dans vos réponses                               Répondez à chaque question, non avec votre intellect, en fonction de ce que vous pensez, mais par la réponse que donne votre CORPS à la question posée                                                                                       Il est très fréquent, pour ne pas dire constant, que l’on remplisse plusieurs paragraphes                                                                Ne cherchez pas à être cohérent dans vos réponses                                                                                              Encore une fois dites ce que votre corps vous dit                                 A la fin du questionnaire vous pourrez ajouter des commentaires qui vous paraissent nécessaire '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef76',
            field=models.CharField(max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef77',
            field=models.CharField(max_length=200, null=True, verbose_name='Feng Bi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef78',
            field=models.CharField(max_length=200, null=True, verbose_name='Han Bi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef79',
            field=models.CharField(max_length=200, null=True, verbose_name='Shi Bi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef8',
            field=models.CharField(max_length=200, null=True, verbose_name='LHUMIDITÉ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef80',
            field=models.CharField(max_length=200, null=True, verbose_name='Re Bi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef81',
            field=models.CharField(max_length=200, null=True, verbose_name='Xue Qi Xu'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef82',
            field=models.CharField(max_length=200, null=True, verbose_name='Yin Qi Xu'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef83',
            field=models.CharField(max_length=200, null=True, verbose_name='Yang Qi Xu'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef9',
            field=models.CharField(max_length=200, null=True, verbose_name='LE CHAUD'),
        ),
    ]
