# Generated by Django 4.0.6 on 2022-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0029_remove_contact_commentaires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Avez_vous_labdomen_dans_son_ensemble_g',
            new_name='Avez_vous_labdomen_dans_son_ensemble_dur',
        ),
        migrations.AddField(
            model_name='contact',
            name='Avez_vous_labdomen_dans_son_ensemble_mou',
            field=models.BooleanField(default=False, verbose_name='Avez-vous l’abdomen dans son ensemble, gonflé, MOU, sensible à la pression ?   '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef14bis',
            field=models.CharField(max_length=200, null=True, verbose_name='Avez_vous une sensation de SÈCHERESSE : '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef14',
            field=models.CharField(max_length=200, null=True, verbose_name='SENSATION ALTERNÉE DE CHAUD ET DE FROID'),
        ),
    ]
