# Generated by Django 4.0.6 on 2022-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0031_alter_contact_commentaires_f1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Commentaires_f8_1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='Commentaires_f8_2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef84',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' - EMOTIONS -'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef85',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mettez une X quand la réponse est nettement OUI, avec commentaires si nécessaire dans la case «\xa0COMMENTAIRES\xa0»'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef86',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AVEZ-VOUS TENDANCE À...'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_mef92',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ACTUELLEMENT'),
        ),
        migrations.AddField(
            model_name='contact',
            name='avoir_PEUR',
            field=models.BooleanField(default=False, verbose_name='"avoir PEUR ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_en_conflit_affectif',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous en conflit affectif avec, conjoint, enfants, parents ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_en_deuil',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous en deuil ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_en_procedure_judiciaire',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous en procédure judiciaire ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etes_vous_en_tension_dans_votre_sphere',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous en tension dans votre sphère professionnelle ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etre_EXAGEREMENT_JOYEUX_ou_TRISTE',
            field=models.BooleanField(default=False, verbose_name='"être EXAGÉRÉMENT JOYEUX ou TRISTE ?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='etre_SOUCIEUX_ANXIEUX',
            field=models.BooleanField(default=False, verbose_name='être SOUCIEUX, ANXIEUX ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='etre_TRISTE',
            field=models.BooleanField(default=False, verbose_name='être TRISTE ? '),
        ),
        migrations.AddField(
            model_name='contact',
            name='etre_en_COLERE',
            field=models.BooleanField(default=False, verbose_name='"être en COLÈRE ?'),
        ),
        migrations.AlterField(
            model_name='familleplante',
            name='famille_plante',
            field=models.CharField(max_length=30),
        ),
    ]
