# Generated by Django 4.0.6 on 2022-08-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0033_contact_m1_aggravation_questce_qui_aggrave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='M1_AGGRAVATION_Questce_qui_aggrave',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AGGRAVATION : Qu’est-ce qui aggrave les symptômes du n°1 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_AMeLIORATION_Questce_qui_ameliore',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AMÉLIORATION : Qu’est-ce qui améliore les symptômes du n°1 ? '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_CAUSES_CIRCONSTANCES_INITIALES_des_symp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CAUSES, CIRCONSTANCES INITIALES des symptômes du n°1 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_DEPUIS_QUAND_souffrezvous_des_symptome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DEPUIS QUAND, souffrez-vous des symptômes du n°1 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_Examens_Medicaux',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Examens Médicaux :'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_Quel_est_le_diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Quel est le diagnostic de votre médecin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_Quel_medicament_A_quel_dosage_Quelle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quel médicament? A quel dosage? Quelle posologie? Depuis quand?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M1_Traitements_en_rapport_avec_le_motif',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Traitements en rapport avec le motif n°1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_AGGRAVATION_Questce_qui_aggrave',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AGGRAVATION : Qu’est-ce qui aggrave les symptômes du n°2 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_AMeLIORATION_Questce_qui_ameliore',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AMÉLIORATION : Qu’est-ce qui améliore les symptômes du n°2 ? '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_CAUSES_CIRCONSTANCES_INITIALES_des_symp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CAUSES, CIRCONSTANCES INITIALES des symptômes du n°2 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_DEPUIS_QUAND_souffrezvous_des_symptome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DEPUIS QUAND, souffrez-vous des symptômes du n°2 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_Examens_Medicaux',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Examens Médicaux :'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_Quel_est_le_diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Quel est le diagnostic de votre médecin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_Quel_medicament_A_quel_dosage_Quelle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quel médicament? A quel dosage? Quelle posologie? Depuis quand?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M2_Traitements_en_rapport_avec_le_motif',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Traitements en rapport avec le motif n°2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_AGGRAVATION_Questce_qui_aggrave',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AGGRAVATION : Qu’est-ce qui aggrave les symptômes du n°3 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_AMeLIORATION_Questce_qui_ameliore',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AMÉLIORATION : Qu’est-ce qui améliore les symptômes du n°3 ? '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_CAUSES_CIRCONSTANCES_INITIALES_des_symp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CAUSES, CIRCONSTANCES INITIALES des symptômes du n°3 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_DEPUIS_QUAND_souffrezvous_des_symptome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DEPUIS QUAND, souffrez-vous des symptômes du n°3 ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_Examens_Medicaux',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Examens Médicaux :'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_Quel_est_le_diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Quel est le diagnostic de votre médecin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_Quel_medicament_A_quel_dosage_Quelle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quel médicament? A quel dosage? Quelle posologie? Depuis quand?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='M3_Traitements_en_rapport_avec_le_motif',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='- Traitements en rapport avec le motif n°3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Motif_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motif 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Motif_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motif 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Motif_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motif 3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Operation_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opération 1 : Quelle opération avez-vous eu ?Quand ?Pourquoi ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Operation_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opération 2 : Quelle opération avez-vous eu ?Quand ?Pourquoi ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Operation_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opération 3 : Quelle opération avez-vous eu ?Quand ?Pourquoi ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Traitement_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traitement 1 ( A quel dosage ? Quelle posologie ?Pour quelle indication ?Depuis quand ?)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Traitement_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traitement 2 ( A quel dosage ? Quelle posologie ?Pour quelle indication ?Depuis quand ?)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Traitement_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traitement 3 ( A quel dosage ? Quelle posologie ?Pour quelle indication ?Depuis quand ?)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Traitement_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traitement 4 ( A quel dosage ? Quelle posologie ?Pour quelle indication ?Depuis quand ?)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef100',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2- DESCRIPTION DÉTAILLÉE DU MOTIF N°2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef101',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3- DESCRIPTION DÉTAILLÉE DU MOTIF N°3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef93',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TRAITEMENTS ACTUELS DIFFÉRENTS À CEUX CORRESPONDANTS AUX MOTIFS DE VOTRE CONSULTATION DE CE JOUR (voir plus bas):                                            POUR CHAQUE MÉDICAMENT DONNEZ LES RENSEIGNEMENTS SUIVANTS :                                     A quel dosage? Quelle posologie? Pour quelle indication? Depuis quand?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef94',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ANTECEDENTS CHIRURGICAUX'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef95',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quelles opérations avez-vous eu ?Quand ?Pourquoi ?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef96',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MOTIF(S) DE LA CONSULTATION'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef97',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='listez par ordre de priorité les motifs de votre consultation (maximum 3, le reste apparaitra dans les réponses aux questions)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef98',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VOTRE MÉDECIN TRAITANT'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef99',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1- DESCRIPTION DÉTAILLÉE DU MOTIF N°1'),
        ),
    ]
