# Generated by Django 4.0.6 on 2022-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0034_alter_contact_m1_aggravation_questce_qui_aggrave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='_mef93bis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='POUR CHAQUE MÉDICAMENT DONNEZ LES RENSEIGNEMENTS SUIVANTS : A quel dosage? Quelle posologie? Pour quelle indication? Depuis quand?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='_mef93',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TRAITEMENTS ACTUELS DIFFÉRENTS À CEUX CORRESPONDANTS AUX MOTIFS DE VOTRE CONSULTATION DE CE JOUR (voir plus bas):'),
        ),
    ]
