# Generated by Django 4.0.6 on 2022-08-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0035_contact__mef93bis_alter_contact__mef93'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='_mef98',
            new_name='Medecin',
        ),
    ]
