# Generated by Django 4.0.6 on 2022-08-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0037_contactfx_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactfx',
            options={'verbose_name': 'Contact'},
        ),
    ]
