# Generated by Django 4.0.6 on 2022-08-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0038_alter_contactfx_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactfx',
            name='praticien',
        ),
    ]
