# Generated by Django 4.0.6 on 2022-09-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0041_symptome_alter_contactfrancois_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptome',
            old_name='symptome',
            new_name='symptome_name',
        ),
    ]
