# Generated by Django 4.0.6 on 2022-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0042_rename_symptome_symptome_symptome_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomecause',
            name='explications',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Explications'),
        ),
    ]
