# Generated by Django 4.0.6 on 2022-09-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0043_alter_symptomecause_explications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologieSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptome', models.CharField(blank='', max_length=2000, null=True, verbose_name='Symptome')),
                ('principe_therapeutique', models.CharField(blank='', max_length=2000, null=True, verbose_name='Principe therapeutique')),
                ('explications', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Explications')),
                ('traitement_acu', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Traitement acupuncture')),
                ('traitement_pharma', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Traitement pharmacopée')),
            ],
            options={
                'verbose_name': 'Symptome',
            },
        ),
        migrations.RenameModel(
            old_name='Symptome',
            new_name='Patho',
        ),
        migrations.AlterModelOptions(
            name='patho',
            options={'verbose_name': 'Pathologie'},
        ),
        migrations.RenameField(
            model_name='patho',
            old_name='symptome_name',
            new_name='pathologie_name',
        ),
        migrations.DeleteModel(
            name='SymptomeCause',
        ),
        migrations.AddField(
            model_name='pathologiesymptome',
            name='patho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.patho'),
        ),
    ]
