# Generated by Django 4.0.6 on 2022-09-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0044_pathologiesymptome_alter_patho_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologie_name', models.CharField(blank='', max_length=200, null=True, verbose_name='Pathologie')),
            ],
            options={
                'verbose_name': 'Pathologie',
            },
        ),
        migrations.AlterField(
            model_name='pathologiesymptome',
            name='patho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pathologie'),
        ),
        migrations.DeleteModel(
            name='Patho',
        ),
    ]
