# Generated by Django 4.0.6 on 2022-09-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0045_pathologie_alter_pathologiesymptome_patho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologiesymptome',
            name='principe_therapeutique',
            field=models.TextField(blank='', max_length=2000, null=True, verbose_name='Principe therapeutique'),
        ),
    ]
