# Generated by Django 4.0.6 on 2022-09-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0047_alter_pathologiesymptome_principe_therapeutique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologieCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank='', max_length=2000, null=True, verbose_name='Cause')),
                ('principe_therapeutique', models.CharField(blank='', max_length=2000, null=True, verbose_name='Principe therapeutique')),
                ('explications', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Explications')),
                ('traitement_acu', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Traitement acupuncture')),
                ('traitement_pharma', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Traitement pharmacopée')),
                ('patho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pathologie')),
            ],
            options={
                'verbose_name': 'Cause',
            },
        ),
        migrations.DeleteModel(
            name='PathologieSymptome',
        ),
    ]
