# Generated by Django 4.0.6 on 2022-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0048_pathologiecause_delete_pathologiesymptome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologiecause',
            name='symptome',
            field=models.CharField(blank='', max_length=2000, null=True, verbose_name='Symptome'),
        ),
    ]
