# Generated by Django 4.0.6 on 2022-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0050_alter_pathologiecause_symptome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteprescriptionzangfuqui',
            name='quantite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
