# Generated by Django 4.0.6 on 2022-10-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0052_alter_planteprescriptionjingfang_quantite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plante',
            options={'ordering': ['substance_medicinale']},
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f1_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f2_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f3_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f3_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f3_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f3_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f4_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f4_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f4_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f4_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_10',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f5_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f6_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f7_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f8_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfrancois',
            name='Commentaires_f8_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f1_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f2_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f3_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f3_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f3_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f3_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f4_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f4_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f4_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f4_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_10',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f5_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_6',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_7',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_8',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f6_9',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f7_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f8_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
        migrations.AlterField(
            model_name='contactfx',
            name='Commentaires_f8_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires : '),
        ),
    ]
