# Generated by Django 4.0.6 on 2022-12-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0054_pathologiecause_explications_acu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointGrandeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grande_zone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PointZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30)),
                ('grandeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pointgrandezone')),
            ],
        ),
    ]
