# Generated by Django 4.0.6 on 2022-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0055_pointgrandezone_pointzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('localisationAnatomique', models.CharField(max_length=100)),
                ('maitreTungShenging', models.CharField(blank=True, max_length=100, null=True, verbose_name='Me. Tung Shenging')),
                ('maitreTungIndicationTherapeutique', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Me. Tung Indication Therapeutique')),
                ('maitreHuShenging', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dr. HU Shenging')),
                ('maitreHuIndicationTherapeutique', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Dr. HU Indication Therapeutique')),
                ('maitreLaiShenging', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dr. Lai Shenging')),
                ('maitreLaiIndicationTherapeutique', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Dr. Lai Indication Therapeutique')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pointzone')),
            ],
        ),
    ]
