# Generated by Django 4.0.6 on 2022-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0056_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuShenging',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dr. HU Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreLaiShenging',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dr. Lai Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungShenging',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Me. Tung Shenging'),
        ),
    ]
