# Generated by Django 4.0.6 on 2022-12-20 16:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0057_point_image_alter_point_maitrehushenging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='color1',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='point',
            name='color2',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
