# Generated by Django 4.0.6 on 2022-12-20 16:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0058_point_color1_point_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='localisationAnatomique',
        ),
        migrations.AlterField(
            model_name='point',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='couleur 1'),
        ),
        migrations.AlterField(
            model_name='point',
            name='color2',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='couleur 2'),
        ),
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Schéma'),
        ),
    ]
