# Generated by Django 4.0.6 on 2022-12-27 10:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0060_alter_point_options_alter_pointgrandezone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='maitreHuColor1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Dr. HU couleur 1'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuColor2',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Dr. HU couleur 2'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungColor1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Me. Tung couleur 1'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungColor2',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Me. Tung couleur 2'),
        ),
    ]
