# Generated by Django 4.0.6 on 2022-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0061_alter_point_maitrehucolor1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='zone',
        ),
        migrations.AddField(
            model_name='point',
            name='maitreHu_zone',
            field=models.ManyToManyField(related_name='maitreHu_zone', to='myDB.pointzone', verbose_name='Me. Hu zone'),
        ),
        migrations.AddField(
            model_name='point',
            name='maitreTung_zone',
            field=models.ManyToManyField(related_name='maitreTung_zone', to='myDB.pointzone', verbose_name='Me. Tung zone'),
        ),
    ]
