# Generated by Django 4.0.6 on 2022-12-28 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0062_remove_point_zone_point_maitrehu_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologiecause',
            name='explications_acu',
        ),
        migrations.RemoveField(
            model_name='pathologiecause',
            name='explications_pharma',
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Dr. HU Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True, verbose_name='Dr. HU Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreLaiIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Dr. Lai Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreLaiShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True, verbose_name='Dr. Lai Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Me. Tung Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True, verbose_name='Me. Tung Shenging'),
        ),
    ]
