# Generated by Django 4.0.6 on 2022-12-28 14:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0063_remove_pathologiecause_explications_acu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologiecause',
            name='cause',
            field=ckeditor.fields.RichTextField(blank='', max_length=2000, null=True, verbose_name='Cause'),
        ),
        migrations.AlterField(
            model_name='pathologiecause',
            name='principe_therapeutique',
            field=ckeditor.fields.RichTextField(blank='', max_length=2000, null=True, verbose_name='Principe therapeutique'),
        ),
    ]
