# Generated by Django 4.0.6 on 2022-12-28 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0064_alter_pathologiecause_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='causes',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Causes'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='plantes',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Plantes'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='points_acu',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Points acupuncture'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='prescriptions',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Prescriptions'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='principes_traitements',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Principes de traitements'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='symptomes_explications',
            field=ckeditor.fields.RichTextField(blank=True, max_length=8000, null=True, verbose_name='Symptomes'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='syndrome',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Syndrome'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='syndrome_principal',
            field=ckeditor.fields.RichTextField(blank='', max_length=2000, null=True, verbose_name='Syndrome principal'),
        ),
    ]
