# Generated by Django 4.0.6 on 2022-12-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0066_remove_point_maitrehu_zone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point_PointZone',
            new_name='Point_PointZoneHu',
        ),
        migrations.CreateModel(
            name='Point_PointZoneTung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.point')),
                ('pointZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDB.pointzone')),
            ],
        ),
    ]
