# Generated by Django 4.0.6 on 2023-01-01 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0067_rename_point_pointzone_point_pointzonehu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_pointzonetung',
            name='point',
        ),
        migrations.RemoveField(
            model_name='point_pointzonetung',
            name='pointZone',
        ),
        migrations.AddField(
            model_name='point',
            name='localisationAnatomique',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='point',
            name='maitreHu_zone',
            field=models.ManyToManyField(related_name='maitreHu_zone', to='myDB.pointzone', verbose_name='Me. Hu zone'),
        ),
        migrations.AddField(
            model_name='point',
            name='maitreTung_zone',
            field=models.ManyToManyField(related_name='maitreTung_zone', to='myDB.pointzone', verbose_name='Me. Tung zone'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='plantes',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Plantes'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='points_acu',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Points acupuncture'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='prescriptions',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Prescriptions'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='principes_traitements',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Principes de traitements'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='syndrome',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Syndrome'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='syndrome_principal',
            field=ckeditor.fields.RichTextField(blank='', max_length=5000, null=True, verbose_name='Syndrome principal'),
        ),
        migrations.AlterField(
            model_name='pathologiecause',
            name='explications',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Explications'),
        ),
        migrations.AlterField(
            model_name='pathologiecause',
            name='symptome',
            field=ckeditor.fields.RichTextField(blank='', max_length=5000, null=True, verbose_name='Symptome'),
        ),
        migrations.AlterField(
            model_name='pathologiecause',
            name='traitement_acu',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Traitement acupuncture'),
        ),
        migrations.AlterField(
            model_name='pathologiecause',
            name='traitement_pharma',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Traitement pharmacopée'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Dr. HU Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreHuShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Dr. HU Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreLaiIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Dr. Lai Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreLaiShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Dr. Lai Shenging'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungIndicationTherapeutique',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Me. Tung Indication Therapeutique'),
        ),
        migrations.AlterField(
            model_name='point',
            name='maitreTungShenging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Me. Tung Shenging'),
        ),
        migrations.DeleteModel(
            name='Point_PointZoneHu',
        ),
        migrations.DeleteModel(
            name='Point_PointZoneTung',
        ),
    ]
