# Generated by Django 4.0.6 on 2023-01-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0069_alter_point_localisationanatomique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='image',
        ),
    ]
